### ISSUE TITLE
Does not compile on Mac clang

### ISSUE THREAD

**Issue by jeizenga** [ekg/mmmulti#1]
There may be more issues, but I've spotted a few:
1. `omp.h` does not appear to get included correctly: `error: use of undeclared identifier 'omp_get_num_threads'`
1. We use code from `ips4o` that is hidden behind a C preprocessor macro `_OPENMP`, which is apparently not defined by clang: https://github.com/SaschaWitt/ips4o/blob/master/ips4o/ips4o.hpp#L83
1. mmmultimap constructs vector iterators from pointers, which seems to be a private constructor in the clang STL: e.g. https://github.com/ekg/mmmultimap/blob/master/src/mmmultimap.hpp#L340)
1. The `endian.h` header (included from `main.cpp`) is not platform independent (but also I think it might not actually be used?)

**Comment by ekg** [comment]
I'm going to see if I can get similar failures with clang locally.

From my memory, openmp was always a problem on mac vs. linux, irrespective of the clang/gcc differences.

**Comment by ekg** [comment]
We don't need endian.h anymore, as we're using a comparison based sort now.

**Comment by ekg** [comment]
We can just fork ips4o and remove that compiler macro. We shouldn't be building without openmp support. That noted, I'm looking around to see what the equivalent macro is for this in clang.

**Comment by ekg** [comment]
> We can just fork ips4o and remove that compiler macro. We shouldn't be building without openmp support. That noted, I'm looking around to see what the equivalent macro is for this in clang.

I've done this, now in master.

**Comment by ekg** [comment]
> omp.h does not appear to get included correctly: error: use of undeclared identifier 'omp_get_num_threads'

I don't have any means to debug or fix this. Would you please look into this? I think it's the last blocking issue.
