### ISSUE TITLE
Github Releases?

### ISSUE THREAD

**Issue by nileshpatra** [ekg/mmmulti#6]
Hi, I need to use this in a project and it would be great if you could tag the releases here.

**Comment by nileshpatra** [comment]
@ekg can you please do this as well? Same reason as in [pyrle](https://github.com/pyranges/pyrle/issues/2#issuecomment-645840331) :-)

**Comment by ekg** [comment]
Oh wow, sure!

You're the first other user I'm aware of. Did you find it documented well enough? What classes are you using?

**Comment by ekg** [comment]
I've made the v0.1 release.

**Comment by nileshpatra** [comment]
> Oh wow, sure!
> 
> You're the first other user I'm aware of. Did you find it documented well enough? 

The Readme looks good, however I'm not someone who is well versed in medicine.

> What classes are you using?

I don't personally use this, but see it as a potential software that can go to Debian users - and can be used by people practicing medicine and using Debian or Debian Derivatives (like Ubuntu) - since their upstream is Debian (Debian-Unstable is the upstream for Ubuntu) itself.
And ofcourse, thanks for your work on this! :-)

**Comment by ekg** [comment]
These approaches are helpful for bioinformatics in general, but could be used by other people working on various computational problems where you need a dense multimap, sorted multiset, or interval tree and can't load the data set into main memory.

Thanks for your help!

**Comment by smoe** [comment]
Your software is dragged in via the  https://nf-co.re/viralrecon workflow that last week's Debian Med Covid-19 hackathon addressed. You find an overview on what we are at on https://docs.google.com/spreadsheets/d/1tApLhVqxRZ2VOuMH_aPUgFENQJfbLlB_PFH_Ah_q7hM/edit?usp=sharing . Your guidance towards packages that are yet missing is most welcome.
